let events = [["3/29/2021","NT.AG präsentiert von Gaia-X bei der Digitalagentur Thüringen", "https://www.digitalagentur-thueringen.de/"],
                        ["17/06/2021","NT.AG präsentiert NaLamKI beim Thüringer Digitalfestival", "https://www.thueringerdigitalfestival.de/veranstaltungen"],
                        ["18/06/2021","NaLamKI bei Digitaltag.eu", ""],
                        ["15/07/2021","NaLamKI am Tag der offenen Tür der Hohenheimer Agrartechnik", ""],
                        ["10/09/2021","HHI, TUK und JD bei “Versuchsanstalt für Viehhaltung, Neumühle", ""],
                        ["5/10/2021","JKI Pressemitteilung zum NaLamKI Projekt", "https://www.julius-kuehn.de/media/Presse/2021/PDF/PI2021-24_NaLamKI-Projektstart.pdf"],
                        ["2/11/2021","KI-Technologien für die nachhaltige Landwirtschaft (Fraunhofer Gesellschaft)", "https://www.fraunhofer.de/content/dam/zv/de/presse-medien/2021/november/hhi-ki-technologien-fuer-die-nachhaltige-landwirtschaft.pdf"],
                        ["3/11/2021","KI-Technologien für die nachhaltige Landwirtschaft (Gartenbau Profi)", "https://www.gb-profi.de/nachricht-gemuese/detail/ki-technologien-fuer-die-nachhaltige-landwirtschaft/"],
                        ["3/11/2021","KI für die nachhaltige Landwirtschaft (Circular Technology)", "https://circular-technology.com/ki-fuer-die-nachhaltige-landwirtschaft/"],
                        ["4/11/2021","KI für Landwirtschaft in Zeiten des Klimawandels (Windkraft-Journal)", "https://www.windkraft-journal.de/2021/11/04/ki-technologien-sollen-die-landwirtschaft-in-zeiten-des-klimawandels-nachhaltiger-machen/168582"],
                        ["1/12/2022","KI soll Landwirtschaft nachhaltiger machen (Springer Professional)", "https://www.springerprofessional.de/offhighway/kuenstliche-intelligenz/ki-soll-landwirtschaft-nachhaltiger-machen-/19934922"],
                        ["21/02/2022","NaLamKI bei Jahrestagung der Gesellschaft für Informatik in der Landwirtschaft (GIL)", ""],
                        ["22/02/2022","GIL Vortrag: Multisensorale Informationsgewinnung für die Landwirtschaft", "https://dl.gi.de/bitstream/handle/20.500.12116/38430/GIL2022_Tagungsband_gesamt.pdf?sequence=1&isAllowed=y"],
                        ["25/02/2022","NaLamKI bei der Veranstaltung des VDMA und dem Beirat für NLA",""],
                        ["1/03/2022","Datenerhebung in Obstplantage",""],
                        ["10/03/2022","HHI Beginnt Datenaufnahme von Obstplantage in Brandenburg","javascript:window.location.href=window.website_url+'Artikel1';window.location.reload();"],
                        ["30/03/2022","TUK stellt Lenkvorrichtung für autonome Landmaschine fertig",""],
                        ["6/04/2022","HHI Demonstriert Sidelink Kommunikation mit Landmaschinen", "https://www.youtube.com/watch?v=lheOhk_DJtI"],
                        ["17/05/2022","Datenerhebung durch OptoPresision und die DLG Bernbrug",""],
                        ["17/05/2022","NaLamKI bei Paneldiskussion der BITKOM Digital Farming Conference", "https://www.space2agriculture.de/2022/06/07/bitkom-digital-farming-conference-space-meets-agriculture/"],
                        ["24/05/2022","Erster Blick auf die NaLamKI Plattform für interaktives Machine Learning",""],
                        ["1/06/2022","Planet Fusion: Zeitreihen hochaufgelöster Multispektraldaten",""],
                        ["7/06/2022","NaLamKI-Präsentation beim Forum für digitale Technologien",""],
                        ["10/06/2022","NT.AG: Von der Systemarchitektur zur Implementierung von Cloud Services","javascript:window.location.href=window.website_url+'Artikel2';window.location.reload();"],
                        ["14/06/2022","John Deere beginnt Datenaufnahme von Reihenkulturen an der Neumühle",""],
                        ["14/07/2022","Neues JKI Paper: Improving crop monitoring using spatiotemporal fusion",""],
                        ["19/07/2022","Robotmaker's Agrarroboter im Video", "https://www.youtube.com/watch?v=ePNkF0mi2_M"],
                        ["1/11/2022","NaLamKI bei ITU Fokusgruppe “AI and IoT for Digital Agriculture", "https://icag-csrs2022.org/en"],
                        ["07/06/2022", "Jannes Magnusson (HHI) und Michael Gerstenberger (HHI): Präsentation im Forum Digitale Technologien zum Thema „Nachhaltige Landwirtschaft mit KI: Anwendungen, Methoden, Perspektiven - NaLamKI und der Mehrwert für die Digitalisierung.“", ""],
                        ["24/8/2022", "Raghu Chaliganti (HHI) präsentiert im  ITU/FAO-Workshop 'Large scale digital agriculture: sustainable food systems with IoT and AI'  das NaLamKI-Projekt und erläutert seine landwirtschaftlichen use cases.", ""],
                        ["16/09/2022", "Raghu Chaliganti (HHI) präsentiert im Forum Digitale Technologien zum Thema „Künstliche Intelligenz in Deutschland und Großbritannien – Möglichkeiten der Zusammenarbeit“  nutzerzentrierte Ansätze im NaLamKI-Projekt und Möglichkeiten für eine zukünftige Zusammenarbeit.", ""],
                        ["27/09/2022","NaLamKI bei der Jahrestagung der GI „Informatik in den Naturwissenschaften",""],
                        ["27/09/2022", "Jannes Magnusson (HHI) und Michael Gerstenberger (HHI) stellen im Workshop „Geodaten als open data für die Künstliche Intellgenz“ den Umgang mit Geodatan im NaLamKI-Porjekt vor und tragen Impulse aus dem Projekt in die Diskussion um Open Source in der KI.", ""],
                        ["21/10/2022", "Sebastian Bosse (HHI) stellt auf dem KI-Symposion „Artificial Intelligence for Life“ die Nutzer-zentrierten Ansätze des NaLamKI-Projekts vor", "https://www.hswt-alumni.de/termine/ki-symposium-und-bdquo-artificial-intelligence-for-life-und-ldquo/", ""],
                        ["7/11/2022", "Sebastian Bosse (HHI) berichtet auf dem KI Monday „AI & the future of food” vom NaLamKI-Projekt und wie es Herausforderungen der Interoperabilität adressiert", "https://ki-berlin.de/events/event/ai-monday-berlin-ai-the-future-of-food).", ""],
                        ["23/11/2022", "Sebastian Bosse (HHI) erläutert auf dem Workshop „Identifiying Policy Solutions“ in der Workshopserie „Enabeling policies for digitalization in agriculture” des World Policy Forum, wie NaLamKI Datensouveränität sicherstellt", "https://ki-berlin.de/events/event/ai-monday-berlin-ai-the-future-of-food", ""],
                        ["30/11/2022","Unser Artikel für die Konferenz der GIL-Jahrestagung wurde zur Veröffentlichung akzeptiert. Wir freuen uns darauf, NaLamKI mit seinen Ergebnissen vom 13.-14. Februar 2023 in Osnabrück vorstellen zu dürfen.", ""],
                    ]      
                    
                     
                        
export default events;